name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Render
        run: |
          npm run build
          curl -X POST \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer ${{ secrets.RENDER_TOKEN }}' \
            -d '{"build": true}' \
            https://api.render.com/v1/services/srv-cpjmhjqcn0vc73aou5ng/deploys
